### ISSUE TITLE
Green Points™ are being incrimented when auto adding POIs.

### ISSUE THREAD

**Issue by TechnicalFox** [rywils21/MUTTS-#14]
Populating the map with preexisting POI's and the "you are here" POI are causing the user to get points.

**Comment by TechnicalFox** [comment]
DISCLAIMER: Green Points is not actually trademarked

**Comment by rywils21** [comment]
Fixed by https://github.com/rywils21/MUTTS-/commit/bedcfca3511fa8cfbc4a3a8e920f82edb8ebd446
