### ISSUE TITLE
Finish flow of adding a marker to the map

### ISSUE THREAD

**Issue by rywils21** [rywils21/MUTTS-#2]
Process of a user creating their own POI needs to be finished. Currently has a modal for info about the POI, but does not save and place in a location.

**Comment by ShaydeNofziger** [comment]
Need to add a step to choose the location

**Comment by ShaydeNofziger** [comment]
Update the "Save" button dialog to "Set location" or similar. Next, the user should be prompted to tap the location of the POI on the map. The result should be a new POI marker at the location the user selected.

**Comment by samfalconer** [comment]
Old.
