### ISSUE TITLE
Find way of including common header

### ISSUE THREAD

**Issue by samfalconer** [rywils21/MUTTS-#7]

**Comment by samfalconer** [comment]
Yeah, turns out there is no magical new way of doing this client-side. This is the best way: http://www.html5rocks.com/en/tutorials/webcomponents/imports/

It would be piecemeal and crappy.

Proposing punt to 1.0 (if at all)

**Comment by TechnicalFox** [comment]
So now we have a server, so we can probs do this super easily, but we don't have to, its up to you...

**Comment by samfalconer** [comment]
Doesn't matter
